services:
  # 1. Redis : La file d'attente
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # 2. API : Reçoit les requêtes HTTP
  api:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    network_mode: "host" 
    container_name: nmap-api
    # La ligne 'ports' est supprimée car le mode 'host' expose déjà le port 5000
    environment:
      # On utilise 127.0.0.1 car le conteneur est sur le même réseau que l'hôte
      - CELERY_BROKER_URL=redis://127.0.0.1:6379/0
      #- CELERY_BROKER_URL=redis://redis:6379/0 --- dans le cas d'un réseau Docker ---
    depends_on:
      - redis

  # 3. Worker : Fait le travail lourd (Nmap)
  worker:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    network_mode: "host" # Indispensable ICI pour que Nmap voit le réseau de l'hôte
    container_name: nmap-worker
    command: celery -A tasks worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://127.0.0.1:6379/0
      #- CELERY_BROKER_URL=redis://redis:6379/0 --- dans le cas d'un réseau Docker ---
    depends_on:
      - redis
    cap_add:
      - NET_RAW
      - NET_ADMIN
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M