apiVersion: v1
kind: Service
metadata:
  name: nmap-api-service
spec:
  type: NodePort # Permet l'accès externe via l'IP de Minikube
  selector:
    app: nmap-api
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30000 # On fixe le port pour faciliter les tests (http://192.168.49.2:30000)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nmap-api
spec:
  replicas: 2 # HA : 2 instances de l'API pour ne jamais perdre le service
  selector:
    matchLabels:
      app: nmap-api
  template:
    metadata:
      labels:
        app: nmap-api
    spec:
      containers:
      - name: api
        image: 192.168.1.98:5000/nmap-app:v1
        imagePullPolicy: Always
        # Commande par défaut du Dockerfile (Gunicorn), pas besoin de surcharge ici
        env:
        - name: CELERY_BROKER_URL
          value: "redis://redis-service:6379/0"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"